known:
- {pos: 0, val: 1}
- {pos: 1, val: 0}
- {pos: 2, val: 0}
- {pos: 3, val: 1}
- {pos: 4, val: 0}
- {pos: 5, val: 0}
- {pos: 6, val: 0}
- {pos: 7, val: 1}
- {pos: 8, val: 0}
- {pos: 9, val: 0}
- {pos: 10, val: 0}
- {pos: 11, val: 0}
- {pos: 12, val: 1}
- {pos: 13, val: 0}
- {pos: 14, val: 1}
- {pos: 15, val: 0}
- {pos: 16, val: 0}
- {pos: 17, val: 1}
- {pos: 18, val: 1}
- {pos: 19, val: 1}
- {pos: 20, val: 0}
- {pos: 21, val: 0}
- {pos: 22, val: 1}
- {pos: 23, val: 0}
- {pos: 24, val: 1}
- {pos: 25, val: 1}
- {pos: 26, val: 1}
- {pos: 27, val: 0}
- {pos: 28, val: 0}
- {pos: 29, val: 0}
- {pos: 30, val: 1}
- {pos: 31, val: 0}
- {pos: 32, val: 1}
- {pos: 33, val: 0}
- {pos: 34, val: 1}
- {pos: 35, val: 1}
- {pos: 36, val: 0}
- {pos: 37, val: 0}
- {pos: 38, val: 0}
- {pos: 39, val: 0}
- {pos: 40, val: 0}
- {pos: 41, val: 1}
- {pos: 42, val: 0}
- {pos: 43, val: 1}
- {pos: 44, val: 0}
- {pos: 45, val: 0}
- {pos: 46, val: 0}
- {pos: 47, val: 0}
- {pos: 48, val: 0}
- {pos: 49, val: 1}
- {pos: 50, val: 0}
- {pos: 51, val: 1}
- {pos: 52, val: 1}
- {pos: 53, val: 0}
- {pos: 54, val: 0}
- {pos: 55, val: 0}
- {pos: 56, val: 0}
- {pos: 57, val: 1}
- {pos: 58, val: 0}
- {pos: 59, val: 1}
- {pos: 60, val: 0}
- {pos: 61, val: 0}
- {pos: 62, val: 0}
- {pos: 63, val: 0}
- {pos: 64, val: 0}
- {pos: 65, val: 0}
- {pos: 66, val: 0}
- {pos: 67, val: 0}
- {pos: 68, val: 0}
- {pos: 69, val: 0}
- {pos: 70, val: 0}
- {pos: 71, val: 0}
- {pos: 72, val: 0}
- {pos: 73, val: 0}
- {pos: 74, val: 0}
- {pos: 75, val: 0}
- {pos: 76, val: 0}
- {pos: 77, val: 0}
- {pos: 78, val: 0}
- {pos: 79, val: 0}
- {pos: 80, val: 0}
- {pos: 81, val: 0}
- {pos: 82, val: 0}
- {pos: 83, val: 0}
- {pos: 84, val: 0}
- {pos: 85, val: 0}
- {pos: 86, val: 0}
- {pos: 87, val: 0}
- {pos: 88, val: 1}
- {pos: 89, val: 0}
- {pos: 90, val: 1}
- {pos: 91, val: 1}
- {pos: 92, val: 0}
- {pos: 93, val: 0}
- {pos: 94, val: 0}
- {pos: 95, val: 0}
- {pos: 96, val: 1}
- {pos: 97, val: 0}
- {pos: 98, val: 0}
- {pos: 99, val: 1}
- {pos: 100, val: 0}
- {pos: 101, val: 0}
- {pos: 102, val: 1}
- {pos: 103, val: 0}
- {pos: 104, val: 0}
- {pos: 105, val: 0}
- {pos: 106, val: 0}
- {pos: 107, val: 1}
- {pos: 108, val: 0}
- {pos: 109, val: 0}
- {pos: 110, val: 1}
- {pos: 111, val: 0}
- {pos: 112, val: 0}
- {pos: 113, val: 0}
- {pos: 114, val: 1}
- {pos: 115, val: 0}
- {pos: 116, val: 0}
- {pos: 117, val: 0}
- {pos: 118, val: 1}
- {pos: 119, val: 0}
- {pos: 120, val: 0}
- {pos: 121, val: 1}
- {pos: 122, val: 0}
- {pos: 123, val: 0}
- {pos: 124, val: 1}
- {pos: 125, val: 0}
- {pos: 126, val: 1}
- {pos: 127, val: 0}
- {pos: 128, val: 0}
- {pos: 129, val: 0}
- {pos: 130, val: 0}
- {pos: 131, val: 0}
- {pos: 132, val: 0}
- {pos: 133, val: 0}
- {pos: 134, val: 0}
- {pos: 135, val: 0}
- {pos: 136, val: 0}
- {pos: 137, val: 0}
- {pos: 138, val: 0}
- {pos: 139, val: 0}
- {pos: 140, val: 0}
- {pos: 141, val: 0}
- {pos: 142, val: 0}
- {pos: 143, val: 0}
- {pos: 144, val: 0}
- {pos: 145, val: 1}
- {pos: 146, val: 0}
- {pos: 147, val: 0}
- {pos: 148, val: 0}
- {pos: 149, val: 0}
- {pos: 150, val: 0}
- {pos: 151, val: 0}
- {pos: 152, val: 0}
- {pos: 153, val: 0}
- {pos: 154, val: 0}
- {pos: 155, val: 0}
- {pos: 156, val: 0}
- {pos: 157, val: 0}
- {pos: 158, val: 0}
- {pos: 159, val: 1}
- {pos: 264, val: 0}
- {pos: 265, val: 0}
- {pos: 266, val: 0}
- {pos: 267, val: 0}
- {pos: 268, val: 0}
- {pos: 269, val: 0}
- {pos: 270, val: 0}
- {pos: 271, val: 0}
- {pos: 272, val: 0}
- {pos: 273, val: 0}
- {pos: 274, val: 0}
- {pos: 275, val: 0}
- {pos: 276, val: 0}
- {pos: 277, val: 0}
- {pos: 278, val: 0}
- {pos: 279, val: 0}
- {pos: 280, val: 0}
- {pos: 281, val: 0}
- {pos: 282, val: 0}
- {pos: 283, val: 0}
- {pos: 284, val: 0}
- {pos: 285, val: 0}
- {pos: 286, val: 0}
- {pos: 287, val: 0}
- {pos: 749296, val: 0}
- {pos: 749297, val: 0}
- {pos: 749298, val: 0}
- {pos: 749299, val: 0}
- {pos: 749300, val: 0}
- {pos: 749301, val: 0}
- {pos: 749302, val: 0}
- {pos: 749303, val: 0}
- {pos: 749304, val: 0}
- {pos: 749305, val: 0}
- {pos: 749306, val: 0}
- {pos: 749307, val: 0}
- {pos: 749308, val: 0}
- {pos: 749309, val: 0}
- {pos: 749310, val: 0}
- {pos: 749311, val: 0}
- {pos: 749312, val: 0}
- {pos: 749313, val: 0}
- {pos: 749314, val: 0}
- {pos: 749315, val: 0}
- {pos: 749316, val: 0}
- {pos: 749317, val: 0}
- {pos: 749318, val: 0}
- {pos: 749319, val: 0}
- {pos: 749320, val: 0}
- {pos: 749321, val: 0}
- {pos: 749322, val: 0}
- {pos: 749323, val: 0}
- {pos: 749324, val: 0}
- {pos: 749325, val: 0}
- {pos: 749326, val: 0}
- {pos: 749327, val: 0}
- {pos: 749328, val: 1}
- {pos: 749329, val: 0}
- {pos: 749330, val: 0}
- {pos: 749331, val: 1}
- {pos: 749332, val: 0}
- {pos: 749333, val: 0}
- {pos: 749334, val: 1}
- {pos: 749335, val: 0}
- {pos: 749336, val: 1}
- {pos: 749337, val: 0}
- {pos: 749338, val: 1}
- {pos: 749339, val: 0}
- {pos: 749340, val: 0}
- {pos: 749341, val: 0}
- {pos: 749342, val: 1}
- {pos: 749343, val: 0}
- {pos: 749344, val: 0}
- {pos: 749345, val: 1}
- {pos: 749346, val: 1}
- {pos: 749347, val: 1}
- {pos: 749348, val: 0}
- {pos: 749349, val: 0}
- {pos: 749350, val: 1}
- {pos: 749351, val: 0}
- {pos: 749352, val: 0}
- {pos: 749353, val: 0}
- {pos: 749354, val: 1}
- {pos: 749355, val: 0}
- {pos: 749356, val: 0}
- {pos: 749357, val: 0}
- {pos: 749358, val: 1}
- {pos: 749359, val: 0}
- {pos: 749360, val: 0}
- {pos: 749361, val: 1}
- {pos: 749362, val: 1}
- {pos: 749363, val: 1}
- {pos: 749364, val: 0}
- {pos: 749365, val: 1}
- {pos: 749366, val: 0}
- {pos: 749367, val: 1}
- {pos: 749368, val: 0}
- {pos: 749369, val: 1}
- {pos: 749370, val: 0}
- {pos: 749371, val: 0}
- {pos: 749372, val: 0}
- {pos: 749373, val: 0}
- {pos: 749374, val: 1}
- {pos: 749375, val: 0}
- {pos: 749376, val: 0}
- {pos: 749377, val: 0}
- {pos: 749378, val: 0}
- {pos: 749379, val: 0}
- {pos: 749380, val: 0}
- {pos: 749381, val: 1}
- {pos: 749382, val: 1}
- {pos: 749383, val: 0}
- {pos: 749384, val: 0}
- {pos: 749385, val: 1}
- {pos: 749386, val: 0}
- {pos: 749387, val: 0}
- {pos: 749388, val: 0}
- {pos: 749389, val: 0}
- {pos: 749390, val: 0}
- {pos: 749391, val: 1}
- {pos: 296, val: 0}
- {pos: 297, val: 0}
- {pos: 298, val: 0}
- {pos: 299, val: 0}
- {pos: 300, val: 1}
- {pos: 301, val: 0}
- {pos: 302, val: 1}
- {pos: 303, val: 0}
- {pos: 304, val: 0}
- {pos: 305, val: 0}
- {pos: 306, val: 1}
- {pos: 307, val: 1}
- {pos: 308, val: 0}
- {pos: 309, val: 0}
- {pos: 310, val: 1}
- {pos: 311, val: 0}
- {pos: 312, val: 0}
- {pos: 313, val: 0}
- {pos: 314, val: 1}
- {pos: 315, val: 0}
- {pos: 316, val: 1}
- {pos: 317, val: 0}
- {pos: 318, val: 1}
- {pos: 319, val: 0}
- {pos: 320, val: 1}
- {pos: 321, val: 0}
- {pos: 322, val: 1}
- {pos: 323, val: 0}
- {pos: 324, val: 0}
- {pos: 325, val: 0}
- {pos: 326, val: 1}
- {pos: 327, val: 0}
- {pos: 296, val: 1}
- {pos: 297, val: 0}
- {pos: 298, val: 0}
- {pos: 299, val: 1}
- {pos: 300, val: 0}
- {pos: 301, val: 0}
- {pos: 302, val: 1}
- {pos: 303, val: 0}
- {pos: 304, val: 0}
- {pos: 305, val: 0}
- {pos: 306, val: 1}
- {pos: 307, val: 0}
- {pos: 308, val: 0}
- {pos: 309, val: 0}
- {pos: 310, val: 1}
- {pos: 311, val: 0}
- {pos: 312, val: 1}
- {pos: 313, val: 0}
- {pos: 314, val: 0}
- {pos: 315, val: 0}
- {pos: 316, val: 0}
- {pos: 317, val: 0}
- {pos: 318, val: 1}
- {pos: 319, val: 0}
- {pos: 320, val: 0}
- {pos: 321, val: 0}
- {pos: 322, val: 1}
- {pos: 323, val: 0}
- {pos: 324, val: 1}
- {pos: 325, val: 0}
- {pos: 326, val: 1}
- {pos: 327, val: 0}
- {pos: 296, val: 1}
- {pos: 297, val: 1}
- {pos: 298, val: 0}
- {pos: 299, val: 0}
- {pos: 300, val: 0}
- {pos: 301, val: 1}
- {pos: 302, val: 1}
- {pos: 303, val: 0}
- {pos: 304, val: 0}
- {pos: 305, val: 0}
- {pos: 306, val: 0}
- {pos: 307, val: 1}
- {pos: 308, val: 0}
- {pos: 309, val: 0}
- {pos: 310, val: 1}
- {pos: 311, val: 0}
- {pos: 312, val: 0}
- {pos: 313, val: 1}
- {pos: 314, val: 0}
- {pos: 315, val: 0}
- {pos: 316, val: 1}
- {pos: 317, val: 0}
- {pos: 318, val: 1}
- {pos: 319, val: 0}
- {pos: 320, val: 1}
- {pos: 321, val: 0}
- {pos: 322, val: 1}
- {pos: 323, val: 1}
- {pos: 324, val: 0}
- {pos: 325, val: 0}
- {pos: 326, val: 1}
- {pos: 327, val: 0}
- {pos: 296, val: 1}
- {pos: 297, val: 1}
- {pos: 298, val: 1}
- {pos: 299, val: 0}
- {pos: 300, val: 0}
- {pos: 301, val: 1}
- {pos: 302, val: 1}
- {pos: 303, val: 0}
- {pos: 304, val: 1}
- {pos: 305, val: 0}
- {pos: 306, val: 0}
- {pos: 307, val: 0}
- {pos: 308, val: 0}
- {pos: 309, val: 0}
- {pos: 310, val: 1}
- {pos: 311, val: 0}
- {pos: 312, val: 1}
- {pos: 313, val: 0}
- {pos: 314, val: 1}
- {pos: 315, val: 1}
- {pos: 316, val: 0}
- {pos: 317, val: 0}
- {pos: 318, val: 1}
- {pos: 319, val: 0}
- {pos: 320, val: 1}
- {pos: 321, val: 0}
- {pos: 322, val: 0}
- {pos: 323, val: 0}
- {pos: 324, val: 0}
- {pos: 325, val: 0}
- {pos: 326, val: 1}
- {pos: 327, val: 0}
- {pos: 296, val: 1}
- {pos: 297, val: 1}
- {pos: 298, val: 0}
- {pos: 299, val: 0}
- {pos: 300, val: 1}
- {pos: 301, val: 1}
- {pos: 302, val: 1}
- {pos: 303, val: 0}
- {pos: 304, val: 0}
- {pos: 305, val: 1}
- {pos: 306, val: 0}
- {pos: 307, val: 0}
- {pos: 308, val: 0}
- {pos: 309, val: 0}
- {pos: 310, val: 1}
- {pos: 311, val: 0}
- {pos: 312, val: 1}
- {pos: 313, val: 0}
- {pos: 314, val: 0}
- {pos: 315, val: 1}
- {pos: 316, val: 0}
- {pos: 317, val: 0}
- {pos: 318, val: 1}
- {pos: 319, val: 0}
- {pos: 320, val: 0}
- {pos: 321, val: 0}
- {pos: 322, val: 1}
- {pos: 323, val: 0}
- {pos: 324, val: 1}
- {pos: 325, val: 0}
- {pos: 326, val: 1}
- {pos: 327, val: 0}
- {pos: 296, val: 0}
- {pos: 297, val: 1}
- {pos: 298, val: 0}
- {pos: 299, val: 0}
- {pos: 300, val: 0}
- {pos: 301, val: 1}
- {pos: 302, val: 1}
- {pos: 303, val: 0}
- {pos: 304, val: 1}
- {pos: 305, val: 1}
- {pos: 306, val: 0}
- {pos: 307, val: 1}
- {pos: 308, val: 0}
- {pos: 309, val: 0}
- {pos: 310, val: 1}
- {pos: 311, val: 0}
- {pos: 312, val: 1}
- {pos: 313, val: 1}
- {pos: 314, val: 1}
- {pos: 315, val: 0}
- {pos: 316, val: 0}
- {pos: 317, val: 0}
- {pos: 318, val: 1}
- {pos: 319, val: 0}
- {pos: 320, val: 0}
- {pos: 321, val: 0}
- {pos: 322, val: 1}
- {pos: 323, val: 0}
- {pos: 324, val: 0}
- {pos: 325, val: 0}
- {pos: 326, val: 1}
- {pos: 327, val: 0}
- {pos: 296, val: 0}
- {pos: 297, val: 0}
- {pos: 298, val: 0}
- {pos: 299, val: 1}
- {pos: 300, val: 0}
- {pos: 301, val: 1}
- {pos: 302, val: 1}
- {pos: 303, val: 0}
- {pos: 304, val: 1}
- {pos: 305, val: 0}
- {pos: 306, val: 0}
- {pos: 307, val: 1}
- {pos: 308, val: 0}
- {pos: 309, val: 0}
- {pos: 310, val: 1}
- {pos: 311, val: 0}
- {pos: 312, val: 1}
- {pos: 313, val: 1}
- {pos: 314, val: 0}
- {pos: 315, val: 0}
- {pos: 316, val: 1}
- {pos: 317, val: 0}
- {pos: 318, val: 1}
- {pos: 319, val: 0}
- {pos: 320, val: 0}
- {pos: 321, val: 0}
- {pos: 322, val: 1}
- {pos: 323, val: 0}
- {pos: 324, val: 1}
- {pos: 325, val: 0}
- {pos: 326, val: 1}
- {pos: 327, val: 0}
- {pos: 296, val: 0}
- {pos: 297, val: 0}
- {pos: 298, val: 1}
- {pos: 299, val: 0}
- {pos: 300, val: 1}
- {pos: 301, val: 1}
- {pos: 302, val: 1}
- {pos: 303, val: 0}
- {pos: 304, val: 0}
- {pos: 305, val: 1}
- {pos: 306, val: 0}
- {pos: 307, val: 0}
- {pos: 308, val: 1}
- {pos: 309, val: 0}
- {pos: 310, val: 1}
- {pos: 311, val: 0}
- {pos: 312, val: 0}
- {pos: 313, val: 1}
- {pos: 314, val: 1}
- {pos: 315, val: 1}
- {pos: 316, val: 0}
- {pos: 317, val: 0}
- {pos: 318, val: 1}
- {pos: 319, val: 0}
- {pos: 320, val: 1}
- {pos: 321, val: 1}
- {pos: 322, val: 0}
- {pos: 323, val: 0}
- {pos: 324, val: 1}
- {pos: 325, val: 0}
- {pos: 326, val: 1}
- {pos: 327, val: 0}
- {pos: 296, val: 0}
- {pos: 297, val: 0}
- {pos: 298, val: 0}
- {pos: 299, val: 0}
- {pos: 300, val: 1}
- {pos: 301, val: 1}
- {pos: 302, val: 1}
- {pos: 303, val: 0}
- {pos: 304, val: 0}
- {pos: 305, val: 0}
- {pos: 306, val: 0}
- {pos: 307, val: 1}
- {pos: 308, val: 0}
- {pos: 309, val: 0}
- {pos: 310, val: 1}
- {pos: 311, val: 0}
- {pos: 312, val: 1}
- {pos: 313, val: 0}
- {pos: 314, val: 0}
- {pos: 315, val: 1}
- {pos: 316, val: 1}
- {pos: 317, val: 0}
- {pos: 318, val: 1}
- {pos: 319, val: 0}
- {pos: 320, val: 1}
- {pos: 321, val: 1}
- {pos: 322, val: 0}
- {pos: 323, val: 0}
- {pos: 324, val: 1}
- {pos: 325, val: 1}
- {pos: 326, val: 1}
- {pos: 327, val: 0}
- {pos: 296, val: 0}
- {pos: 297, val: 0}
- {pos: 298, val: 1}
- {pos: 299, val: 0}
- {pos: 300, val: 1}
- {pos: 301, val: 1}
- {pos: 302, val: 1}
- {pos: 303, val: 0}
- {pos: 304, val: 1}
- {pos: 305, val: 0}
- {pos: 306, val: 0}
- {pos: 307, val: 1}
- {pos: 308, val: 0}
- {pos: 309, val: 0}
- {pos: 310, val: 1}
- {pos: 311, val: 0}
- {pos: 312, val: 1}
- {pos: 313, val: 0}
- {pos: 314, val: 1}
- {pos: 315, val: 1}
- {pos: 316, val: 0}
- {pos: 317, val: 0}
- {pos: 318, val: 1}
- {pos: 319, val: 0}
- {pos: 320, val: 1}
- {pos: 321, val: 0}
- {pos: 322, val: 1}
- {pos: 323, val: 0}
- {pos: 324, val: 0}
- {pos: 325, val: 0}
- {pos: 326, val: 1}
- {pos: 327, val: 0}
- {pos: 296, val: 0}
- {pos: 297, val: 0}
- {pos: 298, val: 1}
- {pos: 299, val: 0}
- {pos: 300, val: 1}
- {pos: 301, val: 1}
- {pos: 302, val: 1}
- {pos: 303, val: 0}
- {pos: 304, val: 1}
- {pos: 305, val: 0}
- {pos: 306, val: 1}
- {pos: 307, val: 0}
- {pos: 308, val: 0}
- {pos: 309, val: 0}
- {pos: 310, val: 1}
- {pos: 311, val: 0}
- {pos: 312, val: 0}
- {pos: 313, val: 0}
- {pos: 314, val: 0}
- {pos: 315, val: 1}
- {pos: 316, val: 1}
- {pos: 317, val: 0}
- {pos: 318, val: 1}
- {pos: 319, val: 0}
- {pos: 320, val: 0}
- {pos: 321, val: 0}
- {pos: 322, val: 1}
- {pos: 323, val: 0}
- {pos: 324, val: 1}
- {pos: 325, val: 1}
- {pos: 326, val: 1}
- {pos: 327, val: 0}
- {pos: 296, val: 0}
- {pos: 297, val: 1}
- {pos: 298, val: 0}
- {pos: 299, val: 1}
- {pos: 300, val: 1}
- {pos: 301, val: 1}
- {pos: 302, val: 1}
- {pos: 303, val: 0}
- {pos: 304, val: 0}
- {pos: 305, val: 0}
- {pos: 306, val: 1}
- {pos: 307, val: 0}
- {pos: 308, val: 1}
- {pos: 309, val: 0}
- {pos: 310, val: 1}
- {pos: 311, val: 0}
- {pos: 312, val: 0}
- {pos: 313, val: 0}
- {pos: 314, val: 0}
- {pos: 315, val: 1}
- {pos: 316, val: 1}
- {pos: 317, val: 0}
- {pos: 318, val: 1}
- {pos: 319, val: 0}
- {pos: 320, val: 0}
- {pos: 321, val: 0}
- {pos: 322, val: 1}
- {pos: 323, val: 0}
- {pos: 324, val: 1}
- {pos: 325, val: 1}
- {pos: 326, val: 1}
- {pos: 327, val: 0}
- {pos: 160, val: 0}
- {pos: 161, val: 0}
- {pos: 162, val: 0}
- {pos: 163, val: 0}
- {pos: 164, val: 0}
- {pos: 165, val: 0}
- {pos: 166, val: 0}
- {pos: 167, val: 0}
- {pos: 168, val: 0}
- {pos: 169, val: 0}
- {pos: 170, val: 0}
- {pos: 171, val: 0}
- {pos: 172, val: 0}
- {pos: 173, val: 0}
- {pos: 174, val: 0}
- {pos: 175, val: 0}
- {pos: 192, val: 1}
- {pos: 193, val: 0}
- {pos: 194, val: 0}
- {pos: 195, val: 0}
- {pos: 196, val: 0}
- {pos: 197, val: 0}
- {pos: 198, val: 0}
- {pos: 199, val: 0}
- {pos: 192, val: 0}
- {pos: 193, val: 1}
- {pos: 194, val: 0}
- {pos: 195, val: 0}
- {pos: 196, val: 0}
- {pos: 197, val: 0}
- {pos: 198, val: 0}
- {pos: 199, val: 0}
- {pos: 192, val: 0}
- {pos: 193, val: 0}
- {pos: 194, val: 1}
- {pos: 195, val: 0}
- {pos: 196, val: 0}
- {pos: 197, val: 0}
- {pos: 198, val: 0}
- {pos: 199, val: 0}
- {pos: 192, val: 0}
- {pos: 193, val: 0}
- {pos: 194, val: 0}
- {pos: 195, val: 1}
- {pos: 196, val: 0}
- {pos: 197, val: 0}
- {pos: 198, val: 0}
- {pos: 199, val: 0}
- {pos: 192, val: 0}
- {pos: 193, val: 0}
- {pos: 194, val: 0}
- {pos: 195, val: 0}
- {pos: 196, val: 1}
- {pos: 197, val: 0}
- {pos: 198, val: 0}
- {pos: 199, val: 0}
- {pos: 200, val: 0}
- {pos: 201, val: 0}
- {pos: 202, val: 0}
- {pos: 203, val: 0}
- {pos: 204, val: 0}
- {pos: 205, val: 0}
- {pos: 206, val: 0}
- {pos: 207, val: 0}
- {pos: 200, val: 0}
- {pos: 201, val: 1}
- {pos: 202, val: 0}
- {pos: 203, val: 0}
- {pos: 204, val: 0}
- {pos: 205, val: 0}
- {pos: 206, val: 0}
- {pos: 207, val: 0}
- {pos: 200, val: 1}
- {pos: 201, val: 1}
- {pos: 202, val: 0}
- {pos: 203, val: 0}
- {pos: 204, val: 0}
- {pos: 205, val: 0}
- {pos: 206, val: 0}
- {pos: 207, val: 0}
- {pos: 200, val: 0}
- {pos: 201, val: 0}
- {pos: 202, val: 1}
- {pos: 203, val: 0}
- {pos: 204, val: 0}
- {pos: 205, val: 0}
- {pos: 206, val: 0}
- {pos: 207, val: 0}
- {pos: 200, val: 0}
- {pos: 201, val: 1}
- {pos: 202, val: 1}
- {pos: 203, val: 0}
- {pos: 204, val: 0}
- {pos: 205, val: 0}
- {pos: 206, val: 0}
- {pos: 207, val: 0}
- {pos: 208, val: 0}
- {pos: 209, val: 0}
- {pos: 210, val: 0}
- {pos: 211, val: 0}
- {pos: 212, val: 0}
- {pos: 213, val: 0}
- {pos: 214, val: 0}
- {pos: 215, val: 0}
- {pos: 216, val: 0}
- {pos: 217, val: 0}
- {pos: 218, val: 0}
- {pos: 219, val: 0}
- {pos: 220, val: 0}
- {pos: 221, val: 0}
- {pos: 222, val: 0}
- {pos: 223, val: 0}
- {pos: 224, val: 0}
- {pos: 225, val: 0}
- {pos: 226, val: 0}
- {pos: 227, val: 0}
- {pos: 228, val: 0}
- {pos: 229, val: 0}
- {pos: 230, val: 0}
- {pos: 231, val: 0}
- {pos: 224, val: 1}
- {pos: 225, val: 0}
- {pos: 226, val: 0}
- {pos: 227, val: 0}
- {pos: 228, val: 0}
- {pos: 229, val: 0}
- {pos: 230, val: 0}
- {pos: 231, val: 0}
lfsr: [408765, 121101, 502609, 860961, 783610, 768241, 843223, 932563]
